import { addIcons } from 'ionicons';
import {
  home,
  people,
  briefcase,
  wallet,
  barChart,
  documentText,
  settings,
  person,
  checkmarkCircle,
  closeCircle,
  bulb,
  add,
  remove,
  logOut,
  menu,
  calendar,
  save,
  storefront,
  peopleCircle,
  search,
  eye,
  create,
  trash,
  personAdd,
  personCircle,
  alertCircle,
  key,
  shieldCheckmark,
  hammerOutline,
  notifications,
  refreshCircle,
  mailOpen,
  clipboard,
  timeOutline,
  cloudUpload,
  pencil,
  trashBin,
  checkmark,
  alert,
  lockClosed,
  lockOpen,
  megaphone,
  chatbubble,
  flag,
  informationCircle,
  calendarClear,
  list,
  download,
  arrowUndo,
  arrowRedo,
  chatbubbles,
  cashOutline,
  chatbox,
  gift,
  send,
  text,
  attach,
  mail,
  pricetag,
  logoFacebook,
  logoInstagram,
  chevronDown, // Ícone desejado
} from 'ionicons/icons';

/**
 * Função responsável por registrar os ícones utilizados no projeto.
 * Deve ser chamada no início da aplicação (ex: no main.ts).
 */
export const registerIcons = (): void => {
  addIcons({
    home,
    people,
    briefcase,
    wallet,
    'bar-chart': barChart,
    'document-text': documentText,
    settings,
    person,
    'checkmark-circle': checkmarkCircle,
    'close-circle': closeCircle,
    bulb,
    add,
    remove,
    'log-out': logOut,
    menu,
    calendar,
    save,
    storefront,
    peopleCircle,
    search,
    eye,
    create,
    trash,
    personAdd,
    personCircle,
    alertCircle,
    key,
    shieldCheckmark,
    'hammer-outline': hammerOutline,
    notifications,
    'refresh-circle': refreshCircle,
    'mail-open': mailOpen,
    clipboard,
    'time-outline': timeOutline,
    'cloud-upload': cloudUpload,
    pencil,
    'trash-bin': trashBin,
    checkmark,
    alert,
    lockClosed,
    lockOpen,
    megaphone,
    chatbubble,
    flag,
    'information-circle': informationCircle,
    'calendar-clear': calendarClear,
    list,
    download,
    'arrow-undo': arrowUndo,
    'arrow-redo': arrowRedo,
    chatbubbles,
    'cash-outline': cashOutline,
    chatbox,
    gift,
    send,
    text,
    attach,
    mail,
    pricetag,
    'logo-facebook': logoFacebook,
    'logo-instagram': logoInstagram,
    'chevron-down': chevronDown, // ✅ Corrigido aqui também
  });
};
