import { addIcons } from 'ionicons';
import {
  home,
  people,
  briefcase,
  wallet,
  barChart,
  documentText,
  settings,
  person,
  checkmarkCircle,
  closeCircle,
  bulb,
  add,
  remove,
  logOut,
  menu,
  calendar,
  save,
  storefront,
  peopleCircle,
  search,
  eye,
  create,
  trash,
  personAdd,
  personCircle,
  alertCircle,
  key,
  shieldCheckmark,
  hammerOutline,
  notifications,
  refreshCircle,
  mailOpen,
  clipboard,
  timeOutline,
  cloudUpload,
  pencil,
  trashBin,
  checkmark,
  alert,
  lockClosed,
  lockOpen,
  megaphone,
  chatbubble,
  flag,
  informationCircle,
  calendarClear,
  list,
  download,
  arrowUndo,
  arrowRedo,
  chatbubbles,
  cashOutline,
  chatbox,
  gift,
  send,
  text,
  attach,
  mail,
  pricetag,
  logoFacebook,
  logoInstagram,
} from 'ionicons/icons';

/**
 * Função responsável por registrar os ícones utilizados no projeto.
 * Deve ser chamada no início da aplicação (ex: no main.ts).
 */
export const registerIcons = (): void => {
  addIcons({
    home: home,
    people: people,
    briefcase: briefcase,
    wallet: wallet,
    'bar-chart': barChart,
    'document-text': documentText,
    settings: settings,
    person: person,
    'checkmark-circle': checkmarkCircle,
    'close-circle': closeCircle,
    bulb: bulb,
    add: add,
    remove: remove,
    'log-out': logOut,
    menu: menu,
    calendar: calendar,
    save: save,
    storefront: storefront,
    peopleCircle: peopleCircle,
    search: search,
    eye: eye,
    create: create,
    trash: trash,
    personAdd: personAdd,
    personCircle: personCircle,
    alertCircle: alertCircle,
    key: key,
    shieldCheckmark: shieldCheckmark,
    'hammer-outline': hammerOutline,
    notifications: notifications,
    'refresh-circle': refreshCircle,
    'mail-open': mailOpen,
    clipboard: clipboard,
    'time-outline': timeOutline,
    'cloud-upload': cloudUpload,
    pencil: pencil,
    'trash-bin': trashBin,
    checkmark: checkmark,
    alert: alert,
    lockClosed: lockClosed,
    lockOpen: lockOpen,
    megaphone: megaphone,
    chatbubble: chatbubble,
    flag: flag,
    'information-circle': informationCircle,
    'calendar-clear': calendarClear,
    list: list,
    download: download,
    'arrow-undo': arrowUndo,
    'arrow-redo': arrowRedo,
    chatbubbles: chatbubbles,
    'cash-outline': cashOutline,
    chatbox: chatbox,
    gift: gift,
    send: send,
    text: text,
    attach: attach,
    mail: mail,
    pricetag: pricetag,
    'logo-facebook': logoFacebook,
    'logo-instagram': logoInstagram,
  });
};
